name: AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

env:
  OPENAI_MODEL: gpt-4.1-mini  # change to o4-mini (or your preferred) if you want deeper reasoning

jobs:
  review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - name: Collect PR diff (unified=0 for precise lines)
        run: |
          git fetch origin "${{ github.base_ref }}"
          git diff --unified=0 "origin/${{ github.base_ref }}"..."${{ github.sha }}" > pr.diff
          wc -c pr.diff || true

      - name: Split diff into manageable chunks
        run: |
          # Split at ~80k bytes per chunk to stay comfortably under token limits
          split -b 80000 -d -a 3 pr.diff chunk_
          ls -l chunk_* || true

      - name: Review each chunk with OpenAI
        id: review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PROMPT_HEADER=$'You are a senior code reviewer. Review this PR diff for:\n'\
          $'- correctness (logic, edge cases)\n'\
          $'- security (inputs, secrets, injections)\n'\
          $'- performance (complexity, allocations, hotspots)\n'\
          $'- tests (coverage, missing cases)\n'\
          $'- readability & API design\n\n'\
          $'Be specific. Use bullet points. Reference filenames and line numbers from the diff hunks.\n'\
          $'Only comment on what you see. If something is fine, be brief. Temperature=0.\n'

          echo "" > review_full.md

          for f in $(ls -1 chunk_* 2>/dev/null || true); do
            DIFF=$(sed "s/`/\\\`/g" "$f")
            BODY=$(jq -nc --arg model "$OPENAI_MODEL" --arg diff "$DIFF" --arg hdr "$PROMPT_HEADER" '
              {
                model: $model,
                temperature: 0,
                input: [
                  {
                    role: "user",
                    content: ($hdr + "\n```diff\n" + $diff + "\n```")
                  }
                ]
              }')

            RESP=$(curl -s https://api.openai.com/v1/responses \
              -H "Authorization: Bearer '$OPENAI_API_KEY'" \
              -H "Content-Type: application/json" \
              -d "$BODY" | jq -r '.output[0].content[0].text // ""')

            printf "\n\n### Review for %s\n\n%s\n" "$f" "$RESP" >> review_full.md
          done

          echo "created=true" >> $GITHUB_OUTPUT

      - name: Post PR comment with GH CLI
        if: steps.review.outputs.created == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          gh pr comment "$PR_NUM" --body-file review_full.md